description: This playbook terminates user's SSO sessions so that upon the next login
  attempt following the unlocking of the account, authentication is required.
id: SafeNet Trusted Access - Terminate User SSO Sessions
inputs:
- description: Username of the user.
  key: userName
  playbookInputQuery:
  required: true
  value:
    simple: ${incident.safenettrustedaccessusername}
- description: Name of the SafeNet Trusted Access integration instance.
  key: instanceName
  playbookInputQuery:
  required: true
  value:
    simple: ${incident.safenettrustedaccessinstancename}
name: SafeNet Trusted Access - Terminate User SSO Sessions
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 83e81935-1505-40c1-8511-ec17fb38c693
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 83e81935-1505-40c1-8511-ec17fb38c693
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: All the SSO sessions successfully deleted.
      closeReason:
        simple: Resolved
      emailclassification: {}
      id:
        simple: ${incident.id}
      safenettrustedaccessremoveuserfromunusualactivitygroup: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 63ce666b-0f70-41b8-83a8-91bd2908dbae
      iscommand: true
      name: Close incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 63ce666b-0f70-41b8-83a8-91bd2908dbae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 1945
        }
      }
  "22":
    continueonerror: true
    id: "22"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      userName:
        complex:
          root: inputs.userName
          transformers:
          - operator: trim
      using:
        simple: ${inputs.instanceName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the profile information for a specific user.
      id: 5c3cfd0d-c26c-4467-85ce-b787d5245e97
      iscommand: true
      name: Get User Information
      script: '|||sta-get-user-info'
      type: regular
      version: -1
    taskid: 5c3cfd0d-c26c-4467-85ce-b787d5245e97
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 895
        }
      }
  "23":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: STA.USER
          operator: isNotEmpty
      label: "yes"
    id: "23"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "38"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the user exist in the tenant.
      id: ac2f1e91-b163-4d37-8702-22f30d065dcc
      iscommand: false
      name: User exist in the tenant ?
      type: condition
      version: -1
    taskid: ac2f1e91-b163-4d37-8702-22f30d065dcc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1070
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: User - ${inputs.userName} doesn't exist in the tenant.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message.
      id: f2a19f98-614b-438c-80e8-b5900ca15f9c
      iscommand: false
      name: Failed Message
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: f2a19f98-614b-438c-80e8-b5900ca15f9c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 1945
        }
      }
  "30":
    id: "30"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: No active SSO session found for the user.
      closeReason:
        simple: Resolved
      emailclassification: {}
      id:
        simple: ${incident.id}
      safenettrustedaccessremoveuserfromunusualactivitygroup: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 71e9cbbe-2117-4883-86e7-90f34d7f2868
      iscommand: true
      name: Close Incident.
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 71e9cbbe-2117-4883-86e7-90f34d7f2868
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1945
        }
      }
  "31":
    continueonerror: true
    id: "31"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "32"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${inputs.instanceName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether you have permission to access the requested tenant.
      id: 1a5fd183-bd1c-4523-83b8-f94c2129b6c3
      iscommand: true
      name: Validate tenant.
      script: '|||sta-validate-tenant'
      type: regular
      version: -1
    taskid: 1a5fd183-bd1c-4523-83b8-f94c2129b6c3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
  "32":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: STA.VALIDATE.TENANT
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: STA.VALIDATE.TENANT
          operator: isTrue
      label: "yes"
    id: "32"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "33"
      "yes":
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check permission of the tenant.
      id: 42acd304-90ae-480c-852e-125907e8e230
      iscommand: false
      name: Check if tenant is accessible?
      type: condition
      version: -1
    taskid: 42acd304-90ae-480c-852e-125907e8e230
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 720
        }
      }
  "33":
    id: "33"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: |-
          Please ensure that the following requirements are fulfilled.
          1. The SafeNet Trusted Access integration instance's name must be the same as the Instance name mentioned in the alert email template.
          2. Ensure that you have the correct Tenant Code or API Key in the SafeNet Trusted Access Integration instance.
          3. Ensure that the integration instance is Enabled.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message.
      id: 68b6de9e-f633-43af-8816-bee01acf3ab1
      iscommand: false
      name: Failed Message
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 68b6de9e-f633-43af-8816-bee01acf3ab1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
  "34":
    id: "34"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      severity:
        simple: "2"
      sla:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: f83a6a8f-6275-4334-8b5e-566abe004201
      iscommand: true
      name: Set Incident Fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: f83a6a8f-6275-4334-8b5e-566abe004201
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "35":
    continueonerror: true
    id: "35"
    ignoreworker: false
    nexttasks:
      "no":
      - "36"
      "yes":
      - "34"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: SafeNet Trusted Access
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 083b2970-6f37-4f5f-8459-d15a1b2c9cdb
      iscommand: false
      name: Is Integration Available
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 083b2970-6f37-4f5f-8459-d15a1b2c9cdb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 195
        }
      }
  "36":
    id: "36"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: No instance found for SafeNet Trusted Access integration.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: e0a26a2e-4a6c-4856-890c-b92886c310cf
      iscommand: false
      name: Failed Message
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: e0a26a2e-4a6c-4856-890c-b92886c310cf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
  "37":
    id: "37"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 673a384a-f9b0-4769-8c0d-2aa93bd4be98
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 673a384a-f9b0-4769-8c0d-2aa93bd4be98
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 2120
        }
      }
  "38":
    id: "38"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "39"
    note: false
    quietmode: 0
    scriptarguments:
      userName:
        simple: ${inputs.userName}
      using:
        simple: ${inputs.instanceName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get sessions for a specific user.
      id: 340ecc55-15a9-4253-8346-51c9337c4aac
      iscommand: true
      name: Get SSO sessions.
      script: '|||sta-get-user-sessions'
      type: regular
      version: -1
    taskid: 340ecc55-15a9-4253-8346-51c9337c4aac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1245
        }
      }
  "39":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: USER
                root: STA
                transformers:
                - args:
                    field:
                      value:
                        simple: sessions
                  operator: getField
          operator: isNotEmpty
      label: "yes"
    id: "39"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "30"
      "yes":
      - "40"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check for active SSO sessions.
      id: 8a14541b-91c7-45f4-8d82-e48626a589d4
      iscommand: false
      name: Check for active SSO sessions.
      type: condition
      version: -1
    taskid: 8a14541b-91c7-45f4-8d82-e48626a589d4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1420
        }
      }
  "40":
    id: "40"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "41"
    note: false
    quietmode: 0
    scriptarguments:
      userName:
        simple: ${inputs.userName}
      using:
        simple: ${inputs.instanceName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete all the active sessions for a specific user from STA.
      id: 4d646224-200e-4c1d-8552-d45de9960adc
      iscommand: true
      name: Terminate all active SSO sessions.
      script: '|||sta-delete-user-sessions'
      type: regular
      version: -1
    taskid: 4d646224-200e-4c1d-8552-d45de9960adc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1595
        }
      }
  "41":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: USER
                root: STA
                transformers:
                - args:
                    field:
                      value:
                        simple: sessions
                  operator: getField
                - args:
                    field:
                      value:
                        simple: Deleted
                  operator: getField
          operator: isTrue
      label: "yes"
    id: "41"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "42"
      "yes":
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if all SSO sessions successfully deleted.
      id: 4840696e-cd7c-4bfe-8362-d594e5402607
      iscommand: false
      name: All the SSO sessions successfully deleted?
      type: condition
      version: -1
    taskid: 4840696e-cd7c-4bfe-8362-d594e5402607
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1770
        }
      }
  "42":
    id: "42"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "37"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Unable to terminate user SSO sessions.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: bc398bcd-c745-4fdf-87c4-1919cf1c67bc
      iscommand: false
      name: Failed message.
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: bc398bcd-c745-4fdf-87c4-1919cf1c67bc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 1945
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 2530,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- Test Playbook STA
fromversion: 6.0.0
